name: Windows Remote Desktop

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Show Windows information
        shell: powershell
        run: |
          Get-ComputerInfo |
            Select-Object WindowsProductName, WindowsVersion, OsBuildNumber

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name 'fDenyTSConnections' `
            -Value 0

          Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'

      - name: Keep runner alive
        shell: powershell
        run: |
          while ($true) {
            Write-Host "Runner is active: $(Get-Date)"
            Start-Sleep -Seconds 60
          }
